// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t *ui_Screen1;
lv_obj_t *ui_LabelDate;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Icon1;
lv_obj_t *ui_Icon2;
lv_obj_t *ui_Icon3;
lv_obj_t *ui_Icon4;
lv_obj_t *ui_Icon5;
lv_obj_t *ui_Icon6;
lv_obj_t *ui_Icon7;
lv_obj_t *ui_Icon8;
lv_obj_t *ui_Icon9;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_pic[29] = {&ui_img_pic50_png, &ui_img_pic51_png, &ui_img_pic52_png, &ui_img_pic53_png, &ui_img_pic54_png, &ui_img_pic60_png, &ui_img_pic61_png, &ui_img_pic62_png, &ui_img_pic63_png, &ui_img_pic64_png, &ui_img_pic65_png, &ui_img_pic70_png, &ui_img_pic71_png, &ui_img_pic72_png, &ui_img_pic73_png, &ui_img_pic74_png, &ui_img_pic75_png, &ui_img_pic76_png, &ui_img_pic77_png, &ui_img_pic80_png, &ui_img_pic81_png, &ui_img_pic82_png, &ui_img_pic83_png, &ui_img_pic84_png, &ui_img_pic85_png, &ui_img_pic90_png, &ui_img_pic91_png, &ui_img_pic92_png, &ui_img_pic93_png};
const lv_img_dsc_t *ui_imgset_tc[4] = {&ui_img_tc1_png, &ui_img_tc10_png, &ui_img_tc3_png, &ui_img_tc9_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////
void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelDate = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LabelDate, 280);
lv_obj_set_height( ui_LabelDate, 48);
lv_obj_set_align( ui_LabelDate, LV_ALIGN_TOP_MID );
lv_label_set_long_mode(ui_LabelDate,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_LabelDate,"2024 Jun 6 (Thu) 19:38");
lv_obj_set_style_text_align(ui_LabelDate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelDate, &ui_font_Font2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LabelDate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LabelDate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_LabelDate, lv_color_hex(0x000060), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_LabelDate, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_LabelDate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_LabelDate, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 0 );
lv_obj_set_y( ui_Label2, 70 );
lv_obj_set_align( ui_Label2, LV_ALIGN_TOP_RIGHT );
lv_label_set_long_mode(ui_Label2,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_Label2,"降雨: 0 mm\nUV: 0.1");
lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &ui_font_Font2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Label2, lv_color_hex(0x777777), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label2, 127, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label2, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label2, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label2, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label2, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_height( ui_Label1, 50);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Label1, 0 );
lv_obj_set_y( ui_Label1, 20 );
lv_obj_set_align( ui_Label1, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_Label1,"27℃ 87%");
lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &ui_font_Font1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Label1, lv_color_hex(0x000060), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label1, 127, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Label1, lv_color_hex(0x777777), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_Label1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Label1, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label1, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label1, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label1, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label1, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Icon1 = lv_img_create(ui_Screen1);
lv_obj_set_width( ui_Icon1, 50);
lv_obj_set_height( ui_Icon1, 50);
lv_obj_set_x( ui_Icon1, 10 );
lv_obj_set_y( ui_Icon1, 22 );
lv_obj_add_flag( ui_Icon1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Icon1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Icon2 = lv_img_create(ui_Screen1);
lv_obj_set_width( ui_Icon2, 50);
lv_obj_set_height( ui_Icon2, 50);
lv_obj_set_x( ui_Icon2, 10 );
lv_obj_set_y( ui_Icon2, 76 );
lv_obj_add_flag( ui_Icon2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Icon2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Icon3 = lv_img_create(ui_Screen1);
lv_obj_set_width( ui_Icon3, 50);
lv_obj_set_height( ui_Icon3, 50);
lv_obj_set_x( ui_Icon3, 10 );
lv_obj_set_y( ui_Icon3, 130 );
lv_obj_add_flag( ui_Icon3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Icon3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Icon4 = lv_img_create(ui_Screen1);
lv_obj_set_width( ui_Icon4, 50);
lv_obj_set_height( ui_Icon4, 50);
lv_obj_set_x( ui_Icon4, 64 );
lv_obj_set_y( ui_Icon4, 76 );
lv_obj_add_flag( ui_Icon4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Icon4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Icon5 = lv_img_create(ui_Screen1);
lv_obj_set_width( ui_Icon5, 50);
lv_obj_set_height( ui_Icon5, 50);
lv_obj_set_x( ui_Icon5, 118 );
lv_obj_set_y( ui_Icon5, 76 );
lv_obj_add_flag( ui_Icon5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Icon5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Icon6 = lv_img_create(ui_Screen1);
lv_obj_set_width( ui_Icon6, 50);
lv_obj_set_height( ui_Icon6, 50);
lv_obj_set_x( ui_Icon6, 64 );
lv_obj_set_y( ui_Icon6, 130 );
lv_obj_add_flag( ui_Icon6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Icon6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Icon7 = lv_img_create(ui_Screen1);
lv_obj_set_width( ui_Icon7, 50);
lv_obj_set_height( ui_Icon7, 50);
lv_obj_set_x( ui_Icon7, 118 );
lv_obj_set_y( ui_Icon7, 130 );
lv_obj_add_flag( ui_Icon7, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Icon7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Icon8 = lv_img_create(ui_Screen1);
lv_obj_set_width( ui_Icon8, 50);
lv_obj_set_height( ui_Icon8, 50);
lv_obj_set_x( ui_Icon8, 172 );
lv_obj_set_y( ui_Icon8, 130 );
lv_obj_add_flag( ui_Icon8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Icon8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Icon9 = lv_img_create(ui_Screen1);
lv_obj_set_width( ui_Icon9, 50);
lv_obj_set_height( ui_Icon9, 50);
lv_obj_set_x( ui_Icon9, 226 );
lv_obj_set_y( ui_Icon9, 130 );
lv_obj_add_flag( ui_Icon9, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Icon9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
