// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_events.h"
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_LabelDate;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Icon1;
extern lv_obj_t *ui_Icon2;
extern lv_obj_t *ui_Icon3;
extern lv_obj_t *ui_Icon4;
extern lv_obj_t *ui_Icon5;
extern lv_obj_t *ui_Icon6;
extern lv_obj_t *ui____initial_actions0;


LV_IMG_DECLARE( ui_img_cold_png);
LV_IMG_DECLARE( ui_img_firer_png);
LV_IMG_DECLARE( ui_img_firey_png);
LV_IMG_DECLARE( ui_img_frost_png);
LV_IMG_DECLARE( ui_img_landslip_png);
LV_IMG_DECLARE( ui_img_ntfl_png);
LV_IMG_DECLARE( ui_img_pic50_png);
LV_IMG_DECLARE( ui_img_pic51_png);
LV_IMG_DECLARE( ui_img_pic52_png);
LV_IMG_DECLARE( ui_img_pic53_png);
LV_IMG_DECLARE( ui_img_pic54_png);
LV_IMG_DECLARE( ui_img_pic60_png);
LV_IMG_DECLARE( ui_img_pic61_png);
LV_IMG_DECLARE( ui_img_pic62_png);
LV_IMG_DECLARE( ui_img_pic63_png);
LV_IMG_DECLARE( ui_img_pic64_png);
LV_IMG_DECLARE( ui_img_pic65_png);
LV_IMG_DECLARE( ui_img_pic70_png);
LV_IMG_DECLARE( ui_img_pic71_png);
LV_IMG_DECLARE( ui_img_pic72_png);
LV_IMG_DECLARE( ui_img_pic73_png);
LV_IMG_DECLARE( ui_img_pic74_png);
LV_IMG_DECLARE( ui_img_pic75_png);
LV_IMG_DECLARE( ui_img_pic76_png);
LV_IMG_DECLARE( ui_img_pic77_png);
LV_IMG_DECLARE( ui_img_pic80_png);
LV_IMG_DECLARE( ui_img_pic81_png);
LV_IMG_DECLARE( ui_img_pic82_png);
LV_IMG_DECLARE( ui_img_pic83_png);
LV_IMG_DECLARE( ui_img_pic84_png);
LV_IMG_DECLARE( ui_img_pic85_png);
LV_IMG_DECLARE( ui_img_pic90_png);
LV_IMG_DECLARE( ui_img_pic91_png);
LV_IMG_DECLARE( ui_img_pic92_png);
LV_IMG_DECLARE( ui_img_pic93_png);
LV_IMG_DECLARE( ui_img_raina_png);
LV_IMG_DECLARE( ui_img_rainb_png);
LV_IMG_DECLARE( ui_img_rainr_png);
LV_IMG_DECLARE( ui_img_sms_png);
LV_IMG_DECLARE( ui_img_tc10_png);
LV_IMG_DECLARE( ui_img_tc1_png);
LV_IMG_DECLARE( ui_img_tc3_png);
LV_IMG_DECLARE( ui_img_tc8b_png);
LV_IMG_DECLARE( ui_img_tc8c_png);
LV_IMG_DECLARE( ui_img_tc8d_png);
LV_IMG_DECLARE( ui_img_tc8ne_png);
LV_IMG_DECLARE( ui_img_tc9_png);
LV_IMG_DECLARE( ui_img_ts_png);
LV_IMG_DECLARE( ui_img_tsunami_png);
LV_IMG_DECLARE( ui_img_vhot_png);


LV_FONT_DECLARE( ui_font_Font1);
LV_FONT_DECLARE( ui_font_Font2);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
